<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<font color='Black'>Read the configuration file:-C:\PayuAutomation\automation\Product\Parameters\Config.properties</font></br>]]>
    </line>
    <line>
      <![CDATA[<font color='Black'>Read the environment file:-C:\PayuAutomation\automation\Product\Parameters\PPReplicaRelease.properties</font></br>]]>
    </line>
    <line>
      <![CDATA[<font color='Black'>Test data sheet is:-C:\PayuAutomation\automation\Product\Parameters\ProductTestData.xls</font></br>]]>
    </line>
    <line>
      <![CDATA[<font color='Black'>Checkout page is:-C:\PayuAutomation\automation\Product\Parameters\README_InputFile.txt</font></br>]]>
    </line>
    <line>
      <![CDATA[<font color='Black'>Results Directory is:-C:\PayuAutomation\automation\Product\test-output</font></br>]]>
    </line>
    <line>
      <![CDATA[<font color='Green'><B>Test 'Test.AdminPanel.Filters.TestBlackListing.blackListedPhoneNoGlobal' Started on '2014-11-11 15:35:20'</B></font></br>]]>
    </line>
    <line>
      <![CDATA[<font color='Black'>Launching 'firefox' browser</font></br>]]>
    </line>
    <line>
      <![CDATA[<font color='Orange'>Retrying the browser launch:-Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'ShishirDwivedi', ip: '10.50.6.155', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_11'
Driver info: driver.version: FirefoxDriver</font></br>]]>
    </line>
    <line>
      <![CDATA[<font color='Black'>Wait for '2' seconds</font></br>]]>
    </line>
    <line>
      <![CDATA[<font color='Black'>Launching 'firefox' browser</font></br>]]>
    </line>
    <line>
      <![CDATA[<font color='Orange'>Retrying the browser launch:-Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'ShishirDwivedi', ip: '10.50.6.155', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_11'
Driver info: driver.version: FirefoxDriver</font></br>]]>
    </line>
    <line>
      <![CDATA[<font color='Black'>Wait for '300' seconds</font></br>]]>
    </line>
    <line>
      <![CDATA[<font color='Orange'>Killing the running browser instances</font></br>]]>
    </line>
    <line>
      <![CDATA[<font color='Black'>Wait for '2' seconds</font></br>]]>
    </line>
    <line>
      <![CDATA[<font color='Black'>Launching 'firefox' browser</font></br>]]>
    </line>
    <line>
      <![CDATA[<font color='Orange'>Retrying the browser launch:-Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'ShishirDwivedi', ip: '10.50.6.155', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_11'
Driver info: driver.version: FirefoxDriver</font></br>]]>
    </line>
  </reporter-output>
  <suite name="Product Automation" duration-ms="320370" started-at="2014-11-11T10:05:20Z" finished-at="2014-11-11T10:10:41Z">
    <groups>
      <group name="1">
        <method signature="TestBlackListing.blackListedPhoneNoGlobal(Utils.Config)[pri:0, instance:Test.AdminPanel.Filters.TestBlackListing@8bd1b6a]" name="blackListedPhoneNoGlobal" class="Test.AdminPanel.Filters.TestBlackListing"/>
      </group> <!-- 1 -->
    </groups>
    <test name="SeamlessStoreCard" duration-ms="320370" started-at="2014-11-11T10:05:20Z" finished-at="2014-11-11T10:10:41Z">
      <class name="Test.AdminPanel.Filters.TestBlackListing">
        <test-method status="PASS" signature="InitializeParameters(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Test.AdminPanel.Filters.TestBlackListing@8bd1b6a]" name="InitializeParameters" is-config="true" duration-ms="16" started-at="2014-11-11T15:35:20Z" finished-at="2014-11-11T15:35:20Z">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
            <param index="1">
              <value is-null="true"/>
            </param>
            <param index="2">
              <value is-null="true"/>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitializeParameters -->
        <test-method status="FAIL" signature="blackListedPhoneNoGlobal(Utils.Config)[pri:0, instance:Test.AdminPanel.Filters.TestBlackListing@8bd1b6a]" name="blackListedPhoneNoGlobal" duration-ms="0" started-at="2014-11-11T15:40:41Z" description=" Verify that a phone Number gets blacklisted for global scope" data-provider="GetTestConfig" finished-at="2014-11-11T15:40:41Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.AssertionError: Ending execution in the middle!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.AssertionError: Ending execution in the middle!
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:161)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:429)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:74)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
Caused by: java.lang.AssertionError: Ending execution in the middle!
	at org.testng.Assert.fail(Assert.java:94)
	at Utils.Log.Fail(Log.java:66)
	at Utils.Config.logFail(Config.java:286)
	at Utils.Config.openBrowser(Config.java:385)
	at Utils.TestBase.GetTestConfig(TestBase.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:135)
	... 26 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- blackListedPhoneNoGlobal -->
        <test-method status="FAIL" signature="tearDown()[pri:0, instance:Test.AdminPanel.Filters.TestBlackListing@8bd1b6a]" name="tearDown" is-config="true" duration-ms="0" started-at="2014-11-11T15:40:41Z" finished-at="2014-11-11T15:40:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
<font color='Red'>Browser could not be opened</font></br>This is generated by soft asset]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
<font color='Red'>Browser could not be opened</font></br>This is generated by soft asset
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at Utils.TestBase.tearDown(TestBase.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.afterRun(TestRunner.java:1014)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:74)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Test.AdminPanel.Filters.TestBlackListing -->
    </test> <!-- SeamlessStoreCard -->
  </suite> <!-- Product Automation -->
</testng-results>
